on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8.0'
          distribution: 'temurin'
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - run: |
          TRANSFER_LOGGING=org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener
          # mvn -B -D$TRANSFER_LOGGING=warn -Dwlp=${{ secrets.WLP }} package tomcat7:redeploy
          mvn --batch-mode -Dwlp=${{ secrets.WLP }} package tomcat7:redeploy
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
